version: "2"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.development
    command: '/bin/bash -c "npm install && npm run watch-node"'
    volumes:
      - ./:/server/
      - 'taskworld_deps:/server/node_modules'
    ports:
      - "3000:3000"
      - "5858:5858"

volumes:
  taskworld_deps: